[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/bwmarrin/discordgo"
  version = "0.19.0"

[[constraint]]
  branch = "master"
  name = "github.com/Necroforger/dgrouter"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "9.0.0"

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.33.1"
