[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/bwmarrin/discordgo"
  version = "0.19.0"

[[constraint]]
  branch = "master"
  name = "github.com/Necroforger/dgrouter"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"
